workdir: /media/share/Member/ueki/datasets
method: daln

task: multiclass

dataset_type: chestxray8
  
sources: ChestXray8/images/source/train

target: ChestXray8/images/target/test

  # source/valを作成した場合だけ有効化する．
  # source_val: source/val

transform:
  resize_size: 256
  random_crop: true

model:
  backbone: resnet50
  num_classes: 12
  pretrained: true
  freeze_features: false

  use_bottleneck: true
  bottleneck_dim: 1024
  dropout: 0.5

train:
  img_size: 224
  batch_size: 32
  num_workers: 0
  drop_last_train: true

  epochs: 50
  iterations_per_epoch: 1000

  feature_lr: 0.001
  classifier_lr: 0.001
  momentum: 0.9
  weight_decay: 0.001
  nesterov: true

  lambda_nwd: 0.1
  use_lr_annealing: true
  seed: 42

grl:
  alpha: 1.0
  lo: 0.0
  hi: 1.0
  max_iters: 30000

tsne:
  checkpoint: outputs/chestxray8/daln_resnet50/checkpoints/best_model.pth
  output_dir: outputs/chestxray8/daln_resnet50/feature_visualization

  source_dataset: source_tsne
  target_dataset: target_test

  max_source: 2000
  max_target: 2000

  batch_size: 32
  num_workers: 0
  require_cuda: true

  pca_dim: 50
  perplexity: 30.0
  max_iter: 1000

evaluation:
  # 論文のTop Accuracyに近い設定．
  selection_mode: target_test


output_dir: outputs/daln/chestxray8_resnet50