workdir: /media/share/Member/ueki/datasets
task:
  type: one_vs_rest

dataset:
  root: /media/share/Member/ueki/datasets/ChestXray8/images
  train: source/train
  test: target/test
  val_ratio: 0.15

transform:
  resize_size: 256
  random_crop: true
  horizontal_flip: 0.5

model:
  backbone: vit_b_16
  pretrained: true
  dropout: 0.0

train:
  img_size: 224
  batch_size: 32
  num_workers: 0
  pin_memory: true
  epochs: 30

  optimizer: adamw
  learning_rate: 0.00001
  weight_decay: 0.0001

  lr_factor: 0.1
  lr_patience: 3

  seed: 42
  require_cuda: true

loss:
  use_pos_weight: true

evaluation:
  selection_metric: pr_auc
  threshold_method: max_f1
  fixed_threshold: 0.5

output_dir: outputs/one_vs_rest/vit_b_16
