experiment_name: china_to_nigeria
setting: source_only

workdir: /media/share/Member/ueki/datasets

sources:
  - name: china
    path: ZhangLabData_binary_dataset

target:
  name: nigeria
  path: nigerian_pneumonia_binary_dataset

classes:
  - NORMAL
  - PNEUMONIA

positive_class: PNEUMONIA

train:
  batch_size: 128
  epochs: 100
  lr: 0.0001
  num_workers: 0
  img_size: 224
  beta1: 0.9
  beta2: 0.999

model:
  name: resnet18
  pretrained: true

output_dir: outputs/china_to_nigeria